-- ⚙️ generated by scripts/gen/redshift_ddl.py from database/01-08_*.sql
-- DO NOT EDIT —— 改表结构请改 Postgres DDL 后重跑本脚本。
-- 转换规则与 DISTKEY/SORTKEY 选型见 redshift_ddl.py 的模块 docstring。

DROP TABLE IF EXISTS ab_test_assignments CASCADE;
CREATE TABLE ab_test_assignments (
    id                       BIGINT,
    user_id                  BIGINT,
    test_id                  INTEGER,
    variant_id               INTEGER,
    assigned_at              TIMESTAMP,
    first_exposure_at        TIMESTAMP
)
DISTKEY(user_id)
SORTKEY(assigned_at);

DROP TABLE IF EXISTS ab_test_variants CASCADE;
CREATE TABLE ab_test_variants (
    variant_id               INTEGER,
    test_id                  INTEGER,
    variant_name             VARCHAR(400),
    variant_key              VARCHAR(200),
    description              VARCHAR(65535),
    traffic_percentage       INTEGER,
    config_json              SUPER,
    is_control               BOOLEAN,
    created_at               TIMESTAMP
)
DISTSTYLE ALL;

DROP TABLE IF EXISTS ab_tests CASCADE;
CREATE TABLE ab_tests (
    test_id                  INTEGER,
    test_name                VARCHAR(800),
    test_key                 VARCHAR(400),
    hypothesis               VARCHAR(65535),
    description              VARCHAR(65535),
    primary_metric           VARCHAR(400),
    secondary_metrics        SUPER,
    target_segment_ids       SUPER,
    traffic_percentage       INTEGER,
    min_sample_size          INTEGER,
    start_date               TIMESTAMP,
    end_date                 TIMESTAMP,
    status                   VARCHAR(80),
    conclusion               VARCHAR(65535),
    winner_variant_id        INTEGER,
    owner                    VARCHAR(200),
    created_at               TIMESTAMP,
    updated_at               TIMESTAMP
)
DISTSTYLE ALL;

DROP TABLE IF EXISTS ad_campaigns CASCADE;
CREATE TABLE ad_campaigns (
    ad_campaign_id           INTEGER,
    channel_id               INTEGER,
    campaign_name            VARCHAR(800),
    campaign_type            VARCHAR(200),
    objective                VARCHAR(200),
    budget_total             DECIMAL(12,2),
    budget_daily             DECIMAL(12,2),
    start_date               DATE,
    end_date                 DATE,
    target_audience          SUPER,
    status                   VARCHAR(80),
    created_at               TIMESTAMP,
    updated_at               TIMESTAMP
)
DISTSTYLE ALL;

DROP TABLE IF EXISTS ad_creatives CASCADE;
CREATE TABLE ad_creatives (
    creative_id              INTEGER,
    ad_campaign_id           INTEGER,
    creative_name            VARCHAR(800),
    creative_type            VARCHAR(200),
    creative_format          VARCHAR(200),
    content_url              VARCHAR(2000),
    headline                 VARCHAR(800),
    description              VARCHAR(65535),
    call_to_action           VARCHAR(200),
    status                   VARCHAR(80),
    created_at               TIMESTAMP
)
DISTSTYLE ALL;

DROP TABLE IF EXISTS banners CASCADE;
CREATE TABLE banners (
    banner_id                INTEGER,
    position                 VARCHAR(200),
    banner_name              VARCHAR(800),
    image_url                VARCHAR(2000),
    target_url               VARCHAR(2000),
    target_type              VARCHAR(200),
    target_id                VARCHAR(400),
    sort_order               INTEGER,
    start_date               TIMESTAMP,
    end_date                 TIMESTAMP,
    is_active                BOOLEAN,
    click_count              INTEGER,
    impression_count         INTEGER,
    created_at               TIMESTAMP,
    updated_at               TIMESTAMP
)
DISTSTYLE ALL;

DROP TABLE IF EXISTS campaigns CASCADE;
CREATE TABLE campaigns (
    campaign_id              INTEGER,
    campaign_name            VARCHAR(800),
    campaign_type            VARCHAR(200),
    description              VARCHAR(65535),
    start_date               TIMESTAMP,
    end_date                 TIMESTAMP,
    target_segment_ids       SUPER,
    budget                   DECIMAL(12,2),
    status                   VARCHAR(80),
    owner                    VARCHAR(200),
    created_at               TIMESTAMP,
    updated_at               TIMESTAMP
)
DISTSTYLE ALL;

DROP TABLE IF EXISTS categories CASCADE;
CREATE TABLE categories (
    category_id              INTEGER,
    parent_id                INTEGER,
    category_name            VARCHAR(400),
    level                    INTEGER,
    sort_order               INTEGER,
    icon_url                 VARCHAR(2000),
    is_active                BOOLEAN,
    created_at               TIMESTAMP,
    updated_at               TIMESTAMP
)
DISTSTYLE ALL;

DROP TABLE IF EXISTS channel_daily_costs CASCADE;
CREATE TABLE channel_daily_costs (
    id                       BIGINT,
    channel_id               INTEGER,
    ad_campaign_id           INTEGER,
    creative_id              INTEGER,
    date                     DATE,
    impressions              BIGINT,
    clicks                   BIGINT,
    installs                 INTEGER,
    cost                     DECIMAL(12,2),
    currency                 VARCHAR(40),
    created_at               TIMESTAMP
)
DISTSTYLE ALL;

DROP TABLE IF EXISTS channels CASCADE;
CREATE TABLE channels (
    channel_id               INTEGER,
    channel_name             VARCHAR(400),
    channel_type             VARCHAR(200),
    platform                 VARCHAR(200),
    description              VARCHAR(65535),
    is_active                BOOLEAN,
    created_at               TIMESTAMP
)
DISTSTYLE ALL;

DROP TABLE IF EXISTS coupons CASCADE;
CREATE TABLE coupons (
    coupon_id                INTEGER,
    coupon_code              VARCHAR(200),
    coupon_name              VARCHAR(800),
    coupon_type              VARCHAR(200),
    discount_value           DECIMAL(10,2),
    min_purchase             DECIMAL(10,2),
    max_discount             DECIMAL(10,2),
    valid_days               INTEGER,
    start_date               TIMESTAMP,
    end_date                 TIMESTAMP,
    total_quota              INTEGER,
    per_user_limit           INTEGER,
    applicable_products      SUPER,
    status                   VARCHAR(80),
    created_at               TIMESTAMP
)
DISTSTYLE ALL;

DROP TABLE IF EXISTS event_definitions CASCADE;
CREATE TABLE event_definitions (
    event_name               VARCHAR(400),
    event_category           VARCHAR(200),
    description              VARCHAR(65535),
    properties_schema        SUPER,
    owner                    VARCHAR(200),
    is_core_event            BOOLEAN,
    created_at               TIMESTAMP,
    updated_at               TIMESTAMP
)
DISTSTYLE ALL;

DROP TABLE IF EXISTS events CASCADE;
CREATE TABLE events (
    event_id                 BIGINT,
    user_id                  BIGINT,
    device_id                VARCHAR(400),
    session_id               BIGINT,
    event_name               VARCHAR(400),
    event_time               TIMESTAMP,
    properties               SUPER,
    page_name                VARCHAR(400),
    referrer                 VARCHAR(800),
    ip_address               VARCHAR(200),
    created_at               TIMESTAMP
)
DISTKEY(user_id)
SORTKEY(event_time);

DROP TABLE IF EXISTS order_items CASCADE;
CREATE TABLE order_items (
    item_id                  BIGINT,
    order_id                 BIGINT,
    product_id               BIGINT,
    product_name             VARCHAR(800),
    sku_id                   BIGINT,
    sku_name                 VARCHAR(800),
    quantity                 INTEGER,
    unit_price               DECIMAL(10,2),
    discount_amount          DECIMAL(10,2),
    actual_amount            DECIMAL(10,2),
    created_at               TIMESTAMP
)
DISTKEY(order_id)
SORTKEY(order_id);

DROP TABLE IF EXISTS orders CASCADE;
CREATE TABLE orders (
    order_id                 BIGINT,
    order_no                 VARCHAR(200),
    user_id                  BIGINT,
    status                   VARCHAR(120),
    total_amount             DECIMAL(12,2),
    discount_amount          DECIMAL(12,2),
    shipping_fee             DECIMAL(10,2),
    actual_amount            DECIMAL(12,2),
    item_count               INTEGER,
    coupon_id                INTEGER,
    shipping_address         SUPER,
    remark                   VARCHAR(65535),
    placed_at                TIMESTAMP,
    paid_at                  TIMESTAMP,
    shipped_at               TIMESTAMP,
    delivered_at             TIMESTAMP,
    cancelled_at             TIMESTAMP,
    cancel_reason            VARCHAR(800),
    refunded_at              TIMESTAMP,
    refund_reason            VARCHAR(800),
    created_at               TIMESTAMP,
    updated_at               TIMESTAMP
)
DISTKEY(user_id)
SORTKEY(placed_at);

DROP TABLE IF EXISTS page_views CASCADE;
CREATE TABLE page_views (
    page_view_id             BIGINT,
    user_id                  BIGINT,
    session_id               BIGINT,
    page_name                VARCHAR(400),
    page_url                 VARCHAR(2000),
    referrer                 VARCHAR(2000),
    duration_seconds         INTEGER,
    scroll_depth_pct         INTEGER,
    view_time                TIMESTAMP,
    created_at               TIMESTAMP
)
DISTKEY(user_id)
SORTKEY(view_time);

DROP TABLE IF EXISTS payments CASCADE;
CREATE TABLE payments (
    payment_id               BIGINT,
    payment_no               VARCHAR(200),
    order_id                 BIGINT,
    user_id                  BIGINT,
    amount                   DECIMAL(12,2),
    payment_method           VARCHAR(200),
    payment_channel          VARCHAR(200),
    status                   VARCHAR(80),
    transaction_id           VARCHAR(400),
    paid_at                  TIMESTAMP,
    failure_reason           VARCHAR(800),
    refund_amount            DECIMAL(12,2),
    refunded_at              TIMESTAMP,
    created_at               TIMESTAMP
)
DISTKEY(user_id)
SORTKEY(created_at);

DROP TABLE IF EXISTS post_comments CASCADE;
CREATE TABLE post_comments (
    comment_id               BIGINT,
    post_id                  BIGINT,
    user_id                  BIGINT,
    parent_comment_id        BIGINT,
    content                  VARCHAR(65535),
    like_count               INTEGER,
    status                   VARCHAR(80),
    created_at               TIMESTAMP
)
DISTKEY(post_id)
SORTKEY(created_at);

DROP TABLE IF EXISTS post_likes CASCADE;
CREATE TABLE post_likes (
    user_id                  BIGINT,
    post_id                  BIGINT,
    created_at               TIMESTAMP
)
DISTKEY(post_id)
SORTKEY(created_at);

DROP TABLE IF EXISTS post_shares CASCADE;
CREATE TABLE post_shares (
    share_id                 BIGINT,
    user_id                  BIGINT,
    post_id                  BIGINT,
    share_channel            VARCHAR(200),
    created_at               TIMESTAMP
)
DISTKEY(post_id)
SORTKEY(created_at);

DROP TABLE IF EXISTS posts CASCADE;
CREATE TABLE posts (
    post_id                  BIGINT,
    user_id                  BIGINT,
    content_type             VARCHAR(200),
    title                    VARCHAR(800),
    content                  VARCHAR(65535),
    media_urls               SUPER,
    tags                     SUPER,
    location                 VARCHAR(400),
    product_ids              SUPER,
    view_count               INTEGER,
    like_count               INTEGER,
    comment_count            INTEGER,
    share_count              INTEGER,
    status                   VARCHAR(80),
    is_featured              BOOLEAN,
    published_at             TIMESTAMP,
    created_at               TIMESTAMP,
    updated_at               TIMESTAMP
)
DISTKEY(post_id)
SORTKEY(published_at);

DROP TABLE IF EXISTS product_tags CASCADE;
CREATE TABLE product_tags (
    id                       INTEGER,
    product_id               BIGINT,
    tag_name                 VARCHAR(200),
    tag_type                 VARCHAR(120),
    created_at               TIMESTAMP
)
DISTSTYLE ALL;

DROP TABLE IF EXISTS products CASCADE;
CREATE TABLE products (
    product_id               BIGINT,
    product_name             VARCHAR(800),
    category_id              INTEGER,
    brand                    VARCHAR(400),
    description              VARCHAR(65535),
    price                    DECIMAL(10,2),
    original_price           DECIMAL(10,2),
    cost                     DECIMAL(10,2),
    stock                    INTEGER,
    sold_count               INTEGER,
    view_count               INTEGER,
    favorite_count           INTEGER,
    rating_avg               DECIMAL(2,1),
    rating_count             INTEGER,
    main_image_url           VARCHAR(2000),
    image_urls               SUPER,
    status                   VARCHAR(80),
    is_featured              BOOLEAN,
    created_at               TIMESTAMP,
    updated_at               TIMESTAMP
)
DISTSTYLE ALL;

DROP TABLE IF EXISTS push_notifications CASCADE;
CREATE TABLE push_notifications (
    push_id                  BIGINT,
    user_id                  BIGINT,
    campaign_id              INTEGER,
    push_type                VARCHAR(200),
    title                    VARCHAR(800),
    content                  VARCHAR(65535),
    deep_link                VARCHAR(2000),
    scheduled_at             TIMESTAMP,
    sent_at                  TIMESTAMP,
    delivered_at             TIMESTAMP,
    opened_at                TIMESTAMP,
    is_delivered             BOOLEAN,
    is_opened                BOOLEAN,
    failure_reason           VARCHAR(800),
    created_at               TIMESTAMP
)
DISTKEY(user_id)
SORTKEY(scheduled_at);

DROP TABLE IF EXISTS sessions CASCADE;
CREATE TABLE sessions (
    session_id               BIGINT,
    user_id                  BIGINT,
    device_id                VARCHAR(400),
    start_time               TIMESTAMP,
    end_time                 TIMESTAMP,
    duration_seconds         INTEGER,
    event_count              INTEGER,
    page_view_count          INTEGER,
    is_bounce                BOOLEAN,
    entry_page               VARCHAR(400),
    exit_page                VARCHAR(400),
    traffic_source           VARCHAR(200),
    utm_source               VARCHAR(200),
    utm_medium               VARCHAR(200),
    utm_campaign             VARCHAR(400),
    created_at               TIMESTAMP
)
DISTKEY(user_id)
SORTKEY(start_time);

DROP TABLE IF EXISTS subscriptions CASCADE;
CREATE TABLE subscriptions (
    subscription_id          BIGINT,
    user_id                  BIGINT,
    plan_name                VARCHAR(400),
    plan_price               DECIMAL(10,2),
    start_date               DATE,
    end_date                 DATE,
    auto_renew               BOOLEAN,
    status                   VARCHAR(80),
    payment_id               BIGINT,
    cancelled_at             TIMESTAMP,
    cancel_reason            VARCHAR(800),
    created_at               TIMESTAMP,
    updated_at               TIMESTAMP
)
DISTKEY(user_id)
SORTKEY(start_date);

DROP TABLE IF EXISTS user_attributions CASCADE;
CREATE TABLE user_attributions (
    attribution_id           BIGINT,
    user_id                  BIGINT,
    channel_id               INTEGER,
    ad_campaign_id           INTEGER,
    creative_id              INTEGER,
    attribution_type         VARCHAR(200),
    click_time               TIMESTAMP,
    install_time             TIMESTAMP,
    attributed_at            TIMESTAMP,
    days_to_install          INTEGER,
    tracking_params          SUPER
)
DISTKEY(user_id)
SORTKEY(click_time);

DROP TABLE IF EXISTS user_coupons CASCADE;
CREATE TABLE user_coupons (
    id                       BIGINT,
    user_id                  BIGINT,
    coupon_id                INTEGER,
    coupon_code              VARCHAR(200),
    received_at              TIMESTAMP,
    expire_at                TIMESTAMP,
    used_at                  TIMESTAMP,
    order_id                 BIGINT,
    status                   VARCHAR(80),
    source                   VARCHAR(200)
)
DISTKEY(user_id)
SORTKEY(received_at);

DROP TABLE IF EXISTS user_devices CASCADE;
CREATE TABLE user_devices (
    device_id                VARCHAR(400),
    user_id                  BIGINT,
    device_type              VARCHAR(80),
    os_version               VARCHAR(80),
    device_model             VARCHAR(200),
    device_brand             VARCHAR(200),
    app_version              VARCHAR(80),
    push_token               VARCHAR(800),
    is_primary               BOOLEAN,
    first_seen_at            TIMESTAMP,
    last_seen_at             TIMESTAMP,
    created_at               TIMESTAMP
)
DISTKEY(user_id)
SORTKEY(first_seen_at);

DROP TABLE IF EXISTS user_follows CASCADE;
CREATE TABLE user_follows (
    follower_id              BIGINT,
    following_id             BIGINT,
    created_at               TIMESTAMP
)
DISTKEY(follower_id)
SORTKEY(created_at);

DROP TABLE IF EXISTS user_messages CASCADE;
CREATE TABLE user_messages (
    message_id               BIGINT,
    sender_id                BIGINT,
    receiver_id              BIGINT,
    content                  VARCHAR(65535),
    message_type             VARCHAR(80),
    related_post_id          BIGINT,
    related_product_id       BIGINT,
    is_read                  BOOLEAN,
    sent_at                  TIMESTAMP,
    read_at                  TIMESTAMP
)
DISTKEY(sender_id)
SORTKEY(sent_at);

DROP TABLE IF EXISTS user_profiles CASCADE;
CREATE TABLE user_profiles (
    user_id                  BIGINT,
    age                      INTEGER,
    gender                   VARCHAR(40),
    birth_date               DATE,
    city                     VARCHAR(200),
    province                 VARCHAR(200),
    country                  VARCHAR(200),
    interests                SUPER,
    occupation               VARCHAR(200),
    income_level             VARCHAR(80),
    created_at               TIMESTAMP,
    updated_at               TIMESTAMP
)
DISTKEY(user_id)
SORTKEY(user_id);

DROP TABLE IF EXISTS user_segment_members CASCADE;
CREATE TABLE user_segment_members (
    user_id                  BIGINT,
    segment_id               INTEGER,
    entered_at               TIMESTAMP,
    exited_at                TIMESTAMP
)
DISTKEY(user_id)
SORTKEY(entered_at);

DROP TABLE IF EXISTS user_segments CASCADE;
CREATE TABLE user_segments (
    segment_id               INTEGER,
    segment_name             VARCHAR(400),
    segment_type             VARCHAR(200),
    description              VARCHAR(65535),
    rules_json               SUPER,
    owner                    VARCHAR(200),
    status                   VARCHAR(80),
    created_at               TIMESTAMP,
    updated_at               TIMESTAMP
)
DISTSTYLE ALL;

DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE users (
    user_id                  BIGINT,
    username                 VARCHAR(200),
    email                    VARCHAR(400),
    phone                    VARCHAR(80),
    registered_at            TIMESTAMP,
    registration_source      VARCHAR(200),
    status                   VARCHAR(80),
    user_level               INTEGER,
    is_vip                   BOOLEAN,
    last_active_at           TIMESTAMP,
    created_at               TIMESTAMP,
    updated_at               TIMESTAMP
)
DISTKEY(user_id)
SORTKEY(registered_at);
